import React, { createContext, useContext } from 'react';

// Diccionario global de traducciones (ampliado a 22 idiomas principales)
export const translations = {
    es: {
        chooseLanguage: 'Elige idioma:',
        welcome: 'Bienvenido',
        register: 'Regístrate',
        login: 'Inicia sesión',
        noAccount: '¿No tienes cuenta?',
        haveAccount: '¿Ya tienes cuenta?',
        clubs: 'Gestión de Clubes',
        national: 'Selecciones Nacionales',
        store: 'Tienda',
        rooms: 'Salas',
        community: 'Comunidad',
        viewer: 'Multi/Match Viewer',
        madness: 'Room Madness',
        premium: 'Premium',
        logout: 'Cerrar sesión',
        mainSlogan: 'Team Soccer Juego de Manager | Únete al mundo del fútbol gratuito',
        landing1: 'Gestiona tu propio club y compite en ligas y copas automáticas',
        landing2: 'Colecciona banderas, trofeos y personaliza tu experiencia',
        landing3: 'Participa en torneos, salas y desafíos comunitarios',
        landing4: 'Disfruta de estadísticas avanzadas y entrenamiento automático',
        landing5: '¡Vive el fútbol como nunca antes, gratis o con ventajas premium!',
    },
    en: {
        chooseLanguage: 'Choose language:',
        welcome: 'Welcome',
        register: 'Register',
        login: 'Login',
        noAccount: "Don't have an account?",
        haveAccount: 'Already have an account?',
        clubs: 'Club Management',
        national: 'National Teams',
        store: 'Store',
        rooms: 'Rooms',
        community: 'Community',
        viewer: 'Multi/Match Viewer',
        madness: 'Room Madness',
        premium: 'Premium',
        logout: 'Logout',
        mainSlogan: 'Team Soccer Manager Game | Join the free football world',
        landing1: 'Manage your own club and compete in automatic leagues and cups',
        landing2: 'Collect flags, trophies and customize your experience',
        landing3: 'Join tournaments, rooms and community challenges',
        landing4: 'Enjoy advanced stats and auto-training',
        landing5: 'Live football like never before, free or with premium advantages!',
    },
    fr: {
        chooseLanguage: 'Choisir la langue :',
        welcome: 'Bienvenue',
        register: "S'inscrire",
        login: 'Connexion',
        noAccount: "Pas de compte ?",
        haveAccount: 'Déjà un compte ?',
        clubs: 'Gestion de Clubs',
        national: 'Équipes Nationales',
        store: 'Boutique',
        rooms: 'Salles',
        community: 'Communauté',
        viewer: 'Multi/Match Viewer',
        madness: 'Room Madness',
        premium: 'Premium',
        logout: 'Déconnexion',
        mainSlogan: 'Team Soccer Manager | Rejoignez le monde du football gratuit',
        landing1: 'Gérez votre club et concourez dans des ligues et coupes automatiques',
        landing2: 'Collectionnez des drapeaux, trophées et personnalisez votre expérience',
        landing3: 'Participez à des tournois, salles et défis communautaires',
        landing4: 'Profitez de statistiques avancées et d’un entraînement automatique',
        landing5: 'Vivez le football comme jamais, gratuit ou avec avantages premium !',
    },
    de: {
        chooseLanguage: 'Sprache wählen:',
        welcome: 'Willkommen',
        register: 'Registrieren',
        login: 'Anmelden',
        noAccount: 'Noch kein Konto?',
        haveAccount: 'Schon ein Konto?',
        clubs: 'Vereinsverwaltung',
        national: 'Nationalmannschaften',
        store: 'Shop',
        rooms: 'Räume',
        community: 'Community',
        viewer: 'Multi/Match Viewer',
        madness: 'Room Madness',
        premium: 'Premium',
        logout: 'Abmelden',
        mainSlogan: 'Team Soccer Manager | Tritt der kostenlosen Fußballwelt bei',
        landing1: 'Verwalte deinen eigenen Club und spiele in automatischen Ligen und Pokalen',
        landing2: 'Sammle Flaggen, Trophäen und passe dein Erlebnis an',
        landing3: 'Nimm an Turnieren, Räumen und Community-Herausforderungen teil',
        landing4: 'Genieße erweiterte Statistiken und Auto-Training',
        landing5: 'Erlebe Fußball wie nie zuvor, kostenlos oder mit Premium-Vorteilen!',
    },
    it: {
        chooseLanguage: 'Scegli lingua:',
        welcome: 'Benvenuto',
        register: 'Registrati',
        login: 'Accedi',
        noAccount: 'Non hai un account?',
        haveAccount: 'Hai già un account?',
        clubs: 'Gestione Club',
        national: 'Nazionali',
        store: 'Negozio',
        rooms: 'Stanze',
        community: 'Comunità',
        viewer: 'Multi/Match Viewer',
        madness: 'Room Madness',
        premium: 'Premium',
        logout: 'Disconnetti',
        mainSlogan: 'Team Soccer Manager | Unisciti al mondo del calcio gratuito',
        landing1: 'Gestisci il tuo club e partecipa a leghe e coppe automatiche',
        landing2: 'Colleziona bandiere, trofei e personalizza la tua esperienza',
        landing3: 'Partecipa a tornei, stanze e sfide della comunità',
        landing4: 'Goditi statistiche avanzate e allenamento automatico',
        landing5: 'Vivi il calcio come mai prima, gratis o con vantaggi premium!',
    },
    pt: {
        chooseLanguage: 'Escolha o idioma:',
        welcome: 'Bem-vindo',
        register: 'Registrar',
        login: 'Entrar',
        noAccount: 'Não tem uma conta?',
        haveAccount: 'Já tem uma conta?',
        clubs: 'Gestão de Clubes',
        national: 'Seleções Nacionais',
        store: 'Loja',
        rooms: 'Salas',
        community: 'Comunidade',
        viewer: 'Multi/Match Viewer',
        madness: 'Room Madness',
        premium: 'Premium',
        logout: 'Sair',
        mainSlogan: 'Team Soccer Manager | Junte-se ao mundo do futebol gratuito',
        landing1: 'Gerencie seu próprio clube e compita em ligas e copas automáticas',
        landing2: 'Colecione bandeiras, troféus e personalize sua experiência',
        landing3: 'Participe de torneios, salas e desafios comunitários',
        landing4: 'Aproveite estatísticas avançadas e treino automático',
        landing5: 'Viva o futebol como nunca antes, grátis ou com vantagens premium!',
    },
    ru: {
        chooseLanguage: 'Выберите язык:',
        welcome: 'Добро пожаловать',
        register: 'Регистрация',
        login: 'Войти',
        noAccount: 'Нет аккаунта?',
        haveAccount: 'Уже есть аккаунт?',
        clubs: 'Управление клубом',
        national: 'Национальные сборные',
        store: 'Магазин',
        rooms: 'Комнаты',
        community: 'Сообщество',
        viewer: 'Multi/Match Viewer',
        madness: 'Room Madness',
        premium: 'Премиум',
        logout: 'Выйти',
        mainSlogan: 'Team Soccer Manager | Присоединяйтесь к бесплатному футбольному миру',
        landing1: 'Управляйте своим клубом и соревнуйтесь в автоматических лигах и кубках',
        landing2: 'Собирайте флаги, трофеи и настраивайте свой опыт',
        landing3: 'Участвуйте в турнирах, комнатах и сообществах',
        landing4: 'Наслаждайтесь расширенной статистикой и авто-тренировкой',
        landing5: 'Испытайте футбол как никогда раньше, бесплатно или с премиум-преимуществами!',
    },
    zh: {
        chooseLanguage: '选择语言：',
        welcome: '欢迎',
        register: '注册',
        login: '登录',
        noAccount: '没有账户？',
        haveAccount: '已有账户？',
        clubs: '俱乐部管理',
        national: '国家队',
        store: '商店',
        rooms: '房间',
        community: '社区',
        viewer: 'Multi/Match Viewer',
        madness: 'Room Madness',
        premium: '高级',
        logout: '登出',
        mainSlogan: 'Team Soccer Manager | 加入免费的足球世界',
        landing1: '管理自己的俱乐部，参加自动联赛和杯赛',
        landing2: '收集旗帜、奖杯并自定义体验',
        landing3: '参加锦标赛、房间和社区挑战',
        landing4: '享受高级统计和自动训练',
        landing5: '前所未有地体验足球，免费或享受高级特权！',
    },
    ja: {
        chooseLanguage: '言語を選択：',
        welcome: 'ようこそ',
        register: '登録',
        login: 'ログイン',
        noAccount: 'アカウントをお持ちでないですか？',
        haveAccount: 'すでにアカウントをお持ちですか？',
        clubs: 'クラブ管理',
        national: 'ナショナルチーム',
        store: 'ストア',
        rooms: 'ルーム',
        community: 'コミュニティ',
        viewer: 'Multi/Match Viewer',
        madness: 'Room Madness',
        premium: 'プレミアム',
        logout: 'ログアウト',
        mainSlogan: 'Team Soccer Manager | 無料サッカーの世界に参加しよう',
        landing1: '自分のクラブを管理し、自動リーグやカップに参加',
        landing2: '旗やトロフィーを集めて体験をカスタマイズ',
        landing3: 'トーナメント、ルーム、コミュニティチャレンジに参加',
        landing4: '高度な統計と自動トレーニングを楽しもう',
        landing5: 'これまでにないサッカー体験を、無料またはプレミアムで！',
    },
    ko: {
        chooseLanguage: '언어 선택:',
        welcome: '환영합니다',
        register: '가입하기',
        login: '로그인',
        noAccount: '계정이 없으신가요?',
        haveAccount: '이미 계정이 있으신가요?',
        clubs: '클럽 관리',
        national: '국가대표팀',
        store: '상점',
        rooms: '룸',
        community: '커뮤니티',
        viewer: 'Multi/Match Viewer',
        madness: 'Room Madness',
        premium: '프리미엄',
        logout: '로그아웃',
        mainSlogan: 'Team Soccer Manager | 무료 축구 세계에 참여하세요',
        landing1: '자신만의 클럽을 관리하고 자동 리그와 컵에 참가하세요',
        landing2: '국기, 트로피를 수집하고 경험을 맞춤화하세요',
        landing3: '토너먼트, 룸, 커뮤니티 챌린지에 참여하세요',
        landing4: '고급 통계와 자동 훈련을 즐기세요',
        landing5: '이전과는 다른 축구를 무료 또는 프리미엄으로 경험하세요!',
    },
    tr: {
        chooseLanguage: 'Dil seçin:',
        welcome: 'Hoş geldiniz',
        register: 'Kayıt ol',
        login: 'Giriş yap',
        noAccount: 'Hesabınız yok mu?',
        haveAccount: 'Zaten hesabınız var mı?',
        clubs: 'Kulüp Yönetimi',
        national: 'Milli Takımlar',
        store: 'Mağaza',
        rooms: 'Odalar',
        community: 'Topluluk',
        viewer: 'Multi/Match Viewer',
        madness: 'Room Madness',
        premium: 'Premium',
        logout: 'Çıkış yap',
        mainSlogan: 'Team Soccer Manager | Ücretsiz futbol dünyasına katıl',
        landing1: 'Kendi kulübünü yönet, otomatik lig ve kupalarda yarış',
        landing2: 'Bayraklar, kupalar topla ve deneyimini kişiselleştir',
        landing3: 'Turnuvalara, odalara ve topluluk mücadelelerine katıl',
        landing4: 'Gelişmiş istatistikler ve otomatik antrenmanın tadını çıkar',
        landing5: 'Futbolu hiç olmadığı gibi yaşa, ücretsiz veya premium avantajlarla!',
    },
    nl: {
        chooseLanguage: 'Kies taal:',
        welcome: 'Welkom',
        register: 'Registreren',
        login: 'Inloggen',
        noAccount: 'Geen account?',
        haveAccount: 'Al een account?',
        clubs: 'Clubbeheer',
        national: 'Nationale Teams',
        store: 'Winkel',
        rooms: 'Kamers',
        community: 'Community',
        viewer: 'Multi/Match Viewer',
        madness: 'Room Madness',
        premium: 'Premium',
        logout: 'Uitloggen',
        mainSlogan: 'Team Soccer Manager | Word lid van de gratis voetbalwereld',
        landing1: 'Beheer je eigen club en doe mee aan automatische competities en bekers',
        landing2: 'Verzamel vlaggen, trofeeën en personaliseer je ervaring',
        landing3: 'Doe mee aan toernooien, kamers en community-uitdagingen',
        landing4: 'Geniet van geavanceerde statistieken en automatisch trainen',
        landing5: 'Beleef voetbal als nooit tevoren, gratis of met premium voordelen!',
    },
    pl: {
        chooseLanguage: 'Wybierz język:',
        welcome: 'Witamy',
        register: 'Zarejestruj się',
        login: 'Zaloguj się',
        noAccount: 'Nie masz konta?',
        haveAccount: 'Masz już konto?',
        clubs: 'Zarządzanie Klubem',
        national: 'Reprezentacje Narodowe',
        store: 'Sklep',
        rooms: 'Pokoje',
        community: 'Społeczność',
        viewer: 'Multi/Match Viewer',
        madness: 'Room Madness',
        premium: 'Premium',
        logout: 'Wyloguj się',
        mainSlogan: 'Team Soccer Manager | Dołącz do darmowego świata piłki nożnej',
        landing1: 'Zarządzaj własnym klubem i rywalizuj w automatycznych ligach i pucharach',
        landing2: 'Zbieraj flagi, trofea i personalizuj swoje doświadczenie',
        landing3: 'Bierz udział w turniejach, pokojach i wyzwaniach społeczności',
        landing4: 'Korzystaj z zaawansowanych statystyk i automatycznego treningu',
        landing5: 'Przeżyj piłkę nożną jak nigdy dotąd, za darmo lub z korzyściami premium!',
    },
    ar: {
        chooseLanguage: 'اختر اللغة:',
        welcome: 'أهلاً وسهلاً',
        register: 'تسجيل',
        login: 'تسجيل الدخول',
        noAccount: 'ليس لديك حساب؟',
        haveAccount: 'هل لديك حساب بالفعل؟',
        clubs: 'إدارة الأندية',
        national: 'المنتخبات الوطنية',
        store: 'المتجر',
        rooms: 'الغرف',
        community: 'المجتمع',
        viewer: 'Multi/Match Viewer',
        madness: 'Room Madness',
        premium: 'بريميوم',
        logout: 'تسجيل الخروج',
        mainSlogan: 'Team Soccer Manager | انضم إلى عالم كرة القدم المجاني',
        landing1: 'قم بإدارة ناديك ونافس في الدوريات والكؤوس التلقائية',
        landing2: 'اجمع الأعلام والكؤوس وخصص تجربتك',
        landing3: 'شارك في البطولات والغرف والتحديات المجتمعية',
        landing4: 'استمتع بإحصائيات متقدمة وتدريب تلقائي',
        landing5: 'عِش كرة القدم كما لم تعشها من قبل، مجانًا أو مع مزايا بريميوم!',
    },
    hi: {
        chooseLanguage: 'भाषा चुनें:',
        welcome: 'स्वागत है',
        register: 'रजिस्टर करें',
        login: 'लॉगिन',
        noAccount: 'कोई खाता नहीं?',
        haveAccount: 'पहले से खाता है?',
        clubs: 'क्लब प्रबंधन',
        national: 'राष्ट्रीय टीमें',
        store: 'स्टोर',
        rooms: 'रूम्स',
        community: 'समुदाय',
        viewer: 'Multi/Match Viewer',
        madness: 'Room Madness',
        premium: 'प्रीमियम',
        logout: 'लॉगआउट',
        mainSlogan: 'Team Soccer Manager | मुफ्त फुटबॉल दुनिया में शामिल हों',
        landing1: 'अपना क्लब प्रबंधित करें और स्वचालित लीग व कप में प्रतिस्पर्धा करें',
        landing2: 'झंडे, ट्रॉफी इकट्ठा करें और अनुभव को अनुकूलित करें',
        landing3: 'टूर्नामेंट, रूम्स और सामुदायिक चुनौतियों में भाग लें',
        landing4: 'उन्नत आँकड़े और ऑटो-ट्रेनिंग का आनंद लें',
        landing5: 'फुटबॉल का अनुभव पहले कभी नहीं, मुफ्त या प्रीमियम के साथ!',
    },
    id: {
        chooseLanguage: 'Pilih bahasa:',
        welcome: 'Selamat datang',
        register: 'Daftar',
        login: 'Masuk',
        noAccount: 'Belum punya akun?',
        haveAccount: 'Sudah punya akun?',
        clubs: 'Manajemen Klub',
        national: 'Tim Nasional',
        store: 'Toko',
        rooms: 'Ruang',
        community: 'Komunitas',
        viewer: 'Multi/Match Viewer',
        madness: 'Room Madness',
        premium: 'Premium',
        logout: 'Keluar',
        mainSlogan: 'Team Soccer Manager | Bergabunglah dengan dunia sepak bola gratis',
        landing1: 'Kelola klub Anda sendiri dan bersaing di liga dan piala otomatis',
        landing2: 'Kumpulkan bendera, trofi dan sesuaikan pengalaman Anda',
        landing3: 'Ikuti turnamen, ruang dan tantangan komunitas',
        landing4: 'Nikmati statistik lanjutan dan pelatihan otomatis',
        landing5: 'Rasakan sepak bola seperti belum pernah sebelumnya, gratis atau dengan keuntungan premium!',
    },
    sv: {
        chooseLanguage: 'Välj språk:',
        welcome: 'Välkommen',
        register: 'Registrera',
        login: 'Logga in',
        noAccount: 'Har du inget konto?',
        haveAccount: 'Har du redan ett konto?',
        clubs: 'Klubbhantering',
        national: 'Landslag',
        store: 'Butik',
        rooms: 'Rum',
        community: 'Community',
        viewer: 'Multi/Match Viewer',
        madness: 'Room Madness',
        premium: 'Premium',
        logout: 'Logga ut',
        mainSlogan: 'Team Soccer Manager | Gå med i den fria fotbollsvärlden',
        landing1: 'Hantera din egen klubb och tävla i automatiska ligor och cuper',
        landing2: 'Samla flaggor, troféer och anpassa din upplevelse',
        landing3: 'Delta i turneringar, rum och community-utmaningar',
        landing4: 'Njut av avancerad statistik och autotränare',
        landing5: 'Upplev fotboll som aldrig förr, gratis eller med premiumfördelar!',
    },
    th: {
        chooseLanguage: 'เลือกภาษา:',
        welcome: 'ยินดีต้อนรับ',
        register: 'สมัครสมาชิก',
        login: 'เข้าสู่ระบบ',
        noAccount: 'ยังไม่มีบัญชี?',
        haveAccount: 'มีบัญชีอยู่แล้ว?',
        clubs: 'การจัดการสโมสร',
        national: 'ทีมชาติ',
        store: 'ร้านค้า',
        rooms: 'ห้อง',
        community: 'ชุมชน',
        viewer: 'Multi/Match Viewer',
        madness: 'Room Madness',
        premium: 'พรีเมียม',
        logout: 'ออกจากระบบ',
        mainSlogan: 'Team Soccer Manager | เข้าร่วมโลกฟุตบอลฟรี',
        landing1: 'บริหารสโมสรของคุณและแข่งขันในลีกและถ้วยอัตโนมัติ',
        landing2: 'สะสมธง ถ้วยรางวัล และปรับแต่งประสบการณ์ของคุณ',
        landing3: 'เข้าร่วมทัวร์นาเมนต์ ห้อง และความท้าทายของชุมชน',
        landing4: 'เพลิดเพลินกับสถิติขั้นสูงและการฝึกอัตโนมัติ',
        landing5: 'สัมผัสฟุตบอลอย่างที่ไม่เคยมีมาก่อน ฟรีหรือพร้อมสิทธิพิเศษพรีเมียม!',
    },
    ro: {
        chooseLanguage: 'Alege limba:',
        welcome: 'Bine ai venit',
        register: 'Înregistrează-te',
        login: 'Autentificare',
        noAccount: 'Nu ai cont?',
        haveAccount: 'Ai deja un cont?',
        clubs: 'Management Club',
        national: 'Echipe Naționale',
        store: 'Magazin',
        rooms: 'Camere',
        community: 'Comunitate',
        viewer: 'Multi/Match Viewer',
        madness: 'Room Madness',
        premium: 'Premium',
        logout: 'Deconectare',
        mainSlogan: 'Team Soccer Manager | Alătură-te lumii fotbalului gratuit',
        landing1: 'Gestionează-ți propriul club și concurează în ligi și cupe automate',
        landing2: 'Colecționează steaguri, trofee și personalizează-ți experiența',
        landing3: 'Participă la turnee, camere și provocări comunitare',
        landing4: 'Bucură-te de statistici avansate și antrenament automat',
        landing5: 'Trăiește fotbalul ca niciodată, gratuit sau cu avantaje premium!',
    },
    el: {
        chooseLanguage: 'Επιλέξτε γλώσσα:',
        welcome: 'Καλώς ήρθατε',
        register: 'Εγγραφή',
        login: 'Σύνδεση',
        noAccount: 'Δεν έχετε λογαριασμό;',
        haveAccount: 'Έχετε ήδη λογαριασμό;',
        clubs: 'Διαχείριση Συλλόγων',
        national: 'Εθνικές Ομάδες',
        store: 'Κατάστημα',
        rooms: 'Δωμάτια',
        community: 'Κοινότητα',
        viewer: 'Multi/Match Viewer',
        madness: 'Room Madness',
        premium: 'Premium',
        logout: 'Αποσύνδεση',
        mainSlogan: 'Team Soccer Manager | Ελάτε στον δωρεάν κόσμο του ποδοσφαίρου',
        landing1: 'Διαχειριστείτε το δικό σας σύλλογο και διαγωνιστείτε σε αυτόματα πρωταθλήματα και κύπελλα',
        landing2: 'Συλλέξτε σημαίες, τρόπαια και προσαρμόστε την εμπειρία σας',
        landing3: 'Συμμετέχετε σε τουρνουά, δωμάτια και κοινοτικές προκλήσεις',
        landing4: 'Απολαύστε προηγμένα στατιστικά και αυτόματη προπόνηση',
        landing5: 'Ζήστε το ποδόσφαιρο όπως ποτέ άλλοτε, δωρεάν ή με premium προνόμια!',
    },
};

export const LanguageContext = createContext({
    language: 'es',
    setLanguage: () => { },
    t: translations['es']
});

export function useLanguage() {
    return useContext(LanguageContext);
}
